# Generated by Django 2.2.8 on 2020-10-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('image', models.ImageField(upload_to='home/')),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('author', models.TextField(max_length=20, verbose_name=rates.models.Profile)),
                ('date_craeted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank='true', default='', upload_to='profile/')),
                ('bio', models.TextField()),
                ('date_craeted', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
